version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: filemanager
      MONGO_INITDB_ROOT_PASSWORD: filemanager

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: filemanager
      ME_CONFIG_MONGODB_ADMINPASSWORD: filemanager
      ME_CONFIG_MONGODB_URL: mongodb://filemanager:filemanager@mongo:27017/
