version: '3.1'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: filemanager
            MONGO_INITDB_ROOT_PASSWORD: filemanager
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - .:/app
            - /app/node_modules
            - /app/www/node_modules
            - "C:/Users/maurizio/.system:/data"
        environment:
            MONGO_HOST: mongo
